### ISSUE TITLE
I can't connect to my Microsoft Sharepoint folder through WebDav

### ISSUE THREAD

**Issue by MCorbo7** [hpp2334/ease-music-player#1]
Setup:

URL: https://example.sharepoint.com/sites/admin/Shared%20documents
Username: myname@domain.com
Password: App password (2FA enabled)

Issue: The app redirects to https://example.sharepoint.com/sites/admin/_layouts/15/Authenticate.aspx, requiring 2FA login, which prevents connection. The same credentials and app password work without issues on Windows.

I've tried alternative URLs and multiple app passwords, but the problem persists. Any insights or guidance would be appreciated.

**Comment by hpp2334** [comment]
Thank you for your feedback~

I'm sorry to say that this app is being refactored to “Android Kotlin Compose + Rust” in the last few months, and the original “flutter + Rust” version is no longer maintained. I will try to reproduce and fix this issue after the refactoring.

**Comment by MCorbo7** [comment]
Thank you so much!

**Comment by hpp2334** [comment]
I tried cadaver and macOS Finder, and they also couldn't treat OneDrive as WebDAV. It seems that accessing the OneDrive API is a more appropriate way to support OneDrive.

**Comment by MCorbo7** [comment]
Thank you so much, I will check it out now

**Comment by MCorbo7** [comment]
I was able to connect alright, it would be perfect if you could add shared folders support, but for everything itself within your onedrive account it's working

**Comment by hpp2334** [comment]
Due to certain reasons, support for shared folders will not be added. I believe that one day storage backend might be provided to users in the form of plugins.
